#####################################
# Telegram bot                      #
# Create a new bot with @BotFather  #
# get TOKEN                         #
#####################################
BOT="B3Server"
BOT_USER="B3Server_bot"
TELEGRAM_GROUP="B3SERVERS"
TOKEN="6537371244:AAHlgzNfhk-VjztTTI2TKxFoLLrYPAwOZcg"