#!/bin/bash

#
# Script para enviar mensagens e arquivos para o Telegram
#
# Autor:            remontti.com.br
# Co-Autor:         samirhv.com.br
# Sponsor:          
# Data:             2024-05-18
# Ultima Atualz.:   2024-05-18
# Versão:           1.0.0
#
#

# VERSAO
VERSION="1.0.0"

# RETORNAR VERSAO
if [ "$1" = "-v" ]; then
  echo "Version: $VERSION"
  exit 0
fi

# Include token
. $0.conf/token.conf

# TROCA O GRUPO
if [ "$2" = "B3SERVERS" ]; then
  CHAT_ID="-1002062314071"
else
  CHAT_ID="-1002062314071"
fi
CHAT_SUB=$3
CHAT_MES=$4

NL="
"
if [ "$1" = "-m" ]; then
  curl --silent -X POST --data-urlencode "chat_id=${CHAT_ID}" --data-urlencode "text=${CHAT_SUB}${NL}${NL}${CHAT_MES}" "https://api.telegram.org/bot${TOKEN}/sendMessage?disable_web_page_preview=true&parse_mode=html" | grep -q '"ok":true' &>/dev/null
elif [ "$1" = "-f" ]; then
  datetime=$(date +%Y%m%d_%H%M)
  file_zip_name="/tmp/$4.${datetime}.zip"
  zip ${file_zip_name} $3 &>/dev/null
  curl -F document=@"${file_zip_name}" -F caption="$5" "https://api.telegram.org/bot${TOKEN}/sendDocument?chat_id=$2" &>/dev/null
  rm ${file_zip_name}
elif [ "$1" = "-t" ]; then
  curl -F document=@"$3" -F caption="$4" "https://api.telegram.org/bot${TOKEN}/sendDocument?chat_id=$2" &>/dev/null
else
  error_file="Error: Lang file not found."
  lang=$(echo $LANG | cut -d. -f1 | cut -c1-2)
  case ${lang} in
  [${lang}]*) msg_lang=msg.${lang} ;;
  esac
  if [ -f $0.conf/lang/${msg_lang} ]; then
    . $0.conf/lang/${msg_lang}
  else
    . $0.conf/lang/msg.en
  fi
  if [ "$#" -ne 1 ]; then
    echo "${inc_no_arg}"
    echo "${usage}"
    exit 1
  fi
fi
exit 0
